version: "3"

services:

  chromedriver:
    build:
      context: .././
      dockerfile: ./docker/chromedriver/Dockerfile
    network_mode: host

  pupil:
    build:
      context: .././
      dockerfile: ./docker/pupil/Dockerfile
    depends_on:
      - chromedriver
      - tutor
      - slate
    network_mode: host

  tutor:
    build:
      context: .././
      dockerfile: ./docker/tutor/Dockerfile
    image: embs/retodjango-tutor
    depends_on:
      - slate
    ports:
      - "3000:5000"

  slate:
    build:
      context: .././
      dockerfile: ./docker/slate/Dockerfile
    image: embs/retodjango-slate
    ports:
      - "3001:8000"
